2024-06-01 10:07:21,268 ERROR: Exception on /home [GET] [in /home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/routes.py", line 108, in index
    return render_template(
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/home/missmandazi/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/missmandazi/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/templates/base.html", line 74, in top-level template code
    {% block content %}
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/templates/index.html", line 47, in block 'content'
    {% include '_post.html' %}
  File "/home/missmandazi/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/templates/_post.html", line 12, in template
    said:{{}}
jinja2.exceptions.TemplateSyntaxError: Expected an expression, got 'end of print statement'
2024-06-01 10:07:40,026 INFO: Tinker Full-stack App [in /mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/__init__.py:63]
2024-06-01 10:10:21,567 INFO: Tinker Full-stack App [in /mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/__init__.py:63]
2024-06-01 10:11:40,475 INFO: Tinker Full-stack App [in /mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/__init__.py:63]
2024-06-01 10:11:50,456 ERROR: Exception on /home [GET] [in /home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/routes.py", line 108, in index
    return render_template(
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/home/missmandazi/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/missmandazi/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/templates/base.html", line 74, in top-level template code
    {% block content %}
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/templates/index.html", line 47, in block 'content'
    {% include '_post.html' %}
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/templates/_post.html", line 12, in top-level template code
    said: {{ moment().startOf('day').fromNow() }}
  File "/home/missmandazi/.local/lib/python3.8/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'flask_moment.moment object' has no attribute 'startOf'
2024-06-01 10:12:22,447 INFO: Tinker Full-stack App [in /mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/__init__.py:63]
2024-06-01 10:12:27,614 ERROR: Exception on /home [GET] [in /home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/routes.py", line 108, in index
    return render_template(
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/home/missmandazi/.local/lib/python3.8/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/home/missmandazi/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/missmandazi/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/templates/base.html", line 74, in top-level template code
    {% block content %}
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/templates/index.html", line 47, in block 'content'
    {% include '_post.html' %}
  File "/mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/templates/_post.html", line 12, in top-level template code
    said: {{ moment().startOf('day').fromNow() }}
  File "/home/missmandazi/.local/lib/python3.8/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'flask_moment.moment object' has no attribute 'startOf'
2024-06-01 10:13:02,815 INFO: Tinker Full-stack App [in /mnt/c/Users/Atuech Obosi/OneDrive/Desktop/software-development(Ayanda)/Chapter-13-Pagination-workthrough-/app/__init__.py:63]
